version: "3"

services:
  pg_database:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - teste-network

volumes:
  pgdata:
    driver: local

networks:
  teste-network: